language: generic
script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  
 jobs:
  include:
    - stage: test
 script: 
  - echo $TRAVIS BRANCH 
     - stage: print
    script: 
   - echo $VIGNESH  VIGNESH
